kind: Deployment
apiVersion: apps/v1
metadata:
  name: kubia-unhealthy-v1
  namespace: default
  labels:
    app: kubia-unhealthy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubia-unhealthy
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 30%    
  template:
    metadata:
      labels:
        app: kubia-unhealthy
    spec:
      containers:
      - image: ualter/kubia:v1-unhealthy
        name: kubia-unhealthy
        ports:
        - containerPort: 9191
        livenessProbe:
          httpGet:
            path: /
            port: 9191              
          initialDelaySeconds: 5
          periodSeconds: 5
        imagePullPolicy: Always   