apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: kubia-healthy
spec:
  replicas: 3
  selector:
    #matchLabels:
    #  app: kubia-healthy
    matchExpressions:
      - key: app
        operator: In
        values:
          - kubia-healthy
  template:
    metadata:
      labels:
        app: kubia-healthy
    spec:
      containers:
      - name: kubia
        image: ualter/kubia:v1-healthy
        ports:
        - containerPort: 9191