# According to Kubernetes v1.17 documentation:
# 
# A ReplicaSet ensures that a specified number of pod replicas are running at any given time. However, 
# a Deployment is a higher-level concept that manages ReplicaSets and provides declarative updates to Pods
# along with a lot of other useful features. Therefore, we recommend using Deployments instead of directly using ReplicaSets,
# unless you require custom update orchestration or don’t require updates at all.

# This actually means that you may never need to manipulate ReplicaSet objects: use a Deployment instead, 
# and define your application in the spec section.
#
# source: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
#

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kubia-healthy
spec:
  replicas: 3
  selector:
    #matchLabels:
    #  app: kubia-healthy
    matchExpressions:
      - key: app
        operator: In
        values:
          - kubia-healthy
  template:
    metadata:
      labels:
        app: kubia-healthy
    spec:
      containers:
      - name: kubia
        image: ualter/kubia:v1-healthy
        ports:
        - containerPort: 9191